public class occurrenceCodons {
    public String[] codons;
    public int[] occurrence;

    public occurrenceCodons() {
        this.codons = new String[64];
        this.codons[0] = "UUU";
        this.codons[1] = "UUC";
        this.codons[2] = "UUA";
        this.codons[3] = "UUG";
        this.codons[4] = "UCU";
        this.codons[5] = "UCC";
        this.codons[6] = "UCA";
        this.codons[7] = "UCG";
        this.codons[8] = "UAU";
        this.codons[9] = "UAC";
        this.codons[10] = "UAA";
        this.codons[11] = "UAG";
        this.codons[12] = "UGU";
        this.codons[13] = "UGC";
        this.codons[14] = "UGA";
        this.codons[15] = "UGG";
        this.codons[16] = "CUU";
        this.codons[17] = "CUC";
        this.codons[18] = "CUA";
        this.codons[19] = "CUG";
        this.codons[20] = "CCU";
        this.codons[21] = "CCC";
        this.codons[22] = "CCA";
        this.codons[23] = "CCG";
        this.codons[24] = "CAU";
        this.codons[25] = "CAC";
        this.codons[26] = "CAA";
        this.codons[27] = "CAG";
        this.codons[28] = "CGU";
        this.codons[29] = "CGC";
        this.codons[30] = "CGA";
        this.codons[31] = "CGG";
        this.codons[32] = "AUU";
        this.codons[33] = "AUC";
        this.codons[34] = "AUA";
        this.codons[35] = "AUG";
        this.codons[36] = "ACU";
        this.codons[37] = "ACC";
        this.codons[38] = "ACA";
        this.codons[39] = "ACG";
        this.codons[40] = "AAU";
        this.codons[41] = "AAC";
        this.codons[42] = "AAA";
        this.codons[43] = "AAG";
        this.codons[44] = "AGU";
        this.codons[45] = "AGC";
        this.codons[46] = "AGA";
        this.codons[47] = "AGG";
        this.codons[48] = "GUU";
        this.codons[49] = "GUC";
        this.codons[50] = "GUA";
        this.codons[51] = "GUG";
        this.codons[52] = "GCU";
        this.codons[53] = "GCC";
        this.codons[54] = "GCA";
        this.codons[55] = "GCG";
        this.codons[56] = "GAU";
        this.codons[57] = "GAC";
        this.codons[58] = "GAA";
        this.codons[59] = "GAG";
        this.codons[60] = "GGU";
        this.codons[61] = "GGC";
        this.codons[62] = "GGA";
        this.codons[63] = "GGG";

        this.occurrence = new int[65];
        for(int i = 0; i < 65; i++) this.occurrence[i] = 0;
    }

    public static int getIndexByCodon(String codon){
        if(codon.equals("UUU")) return 0;
        else if(codon.equals("UUC")) return 1;
        else if(codon.equals("UUA")) return 2;
        else if(codon.equals("UUG")) return 3;
        else if(codon.equals("UCU")) return 4;
        else if(codon.equals("UCC")) return 5;
        else if(codon.equals("UCA")) return 6;
        else if(codon.equals("UCG")) return 7;
        else if(codon.equals("UAU")) return 8;
        else if(codon.equals("UAC")) return 9;
        else if(codon.equals("UAA")) return 10;
        else if(codon.equals("UAG")) return 11;
        else if(codon.equals("UGU")) return 12;
        else if(codon.equals("UGC")) return 13;
        else if(codon.equals("UGA")) return 14;
        else if(codon.equals("UGG")) return 15;
        else if(codon.equals("CUU")) return 16;
        else if(codon.equals("CUC")) return 17;
        else if(codon.equals("CUA")) return 18;
        else if(codon.equals("CUG")) return 19;
        else if(codon.equals("CCU")) return 20;
        else if(codon.equals("CCC")) return 21;
        else if(codon.equals("CCA")) return 22;
        else if(codon.equals("CCG")) return 23;
        else if(codon.equals("CAU")) return 24;
        else if(codon.equals("CAC")) return 25;
        else if(codon.equals("CAA")) return 26;
        else if(codon.equals("CAG")) return 27;
        else if(codon.equals("CGU")) return 28;
        else if(codon.equals("CGC")) return 29;
        else if(codon.equals("CGA")) return 30;
        else if(codon.equals("CGG")) return 31;
        else if(codon.equals("AUU")) return 32;
        else if(codon.equals("AUC")) return 33;
        else if(codon.equals("AUA")) return 34;
        else if(codon.equals("AUG")) return 35;
        else if(codon.equals("ACU")) return 36;
        else if(codon.equals("ACC")) return 37;
        else if(codon.equals("ACA")) return 38;
        else if(codon.equals("ACG")) return 39;
        else if(codon.equals("AAU")) return 40;
        else if(codon.equals("AAC")) return 41;
        else if(codon.equals("AAA")) return 42;
        else if(codon.equals("AAG")) return 43;
        else if(codon.equals("AGU")) return 44;
        else if(codon.equals("AGC")) return 45;
        else if(codon.equals("AGA")) return 46;
        else if(codon.equals("AGG")) return 47;
        else if(codon.equals("GUU")) return 48;
        else if(codon.equals("GUC")) return 49;
        else if(codon.equals("GUA")) return 50;
        else if(codon.equals("GUG")) return 51;
        else if(codon.equals("GCU")) return 52;
        else if(codon.equals("GCC")) return 53;
        else if(codon.equals("GCA")) return 54;
        else if(codon.equals("GCG")) return 55;
        else if(codon.equals("GAU")) return 56;
        else if(codon.equals("GAC")) return 57;
        else if(codon.equals("GAA")) return 58;
        else if(codon.equals("GAG")) return 59;
        else if(codon.equals("GGU")) return 60;
        else if(codon.equals("GGC")) return 61;
        else if(codon.equals("GGA")) return 62;
        else if(codon.equals("GGG")) return 63;
        else return 64;
    }

}